Performing system checks...

System check identified no issues (0 silenced).
March 19, 2020 - 13:11:23
Django version 2.1.11, using settings 'higlass_server.settings'
Starting development server at http://localhost:8001/
Quit the server with CONTROL-C.
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54898)
Traceback (most recent call last):
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
Traceback (most recent call last):
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 288, in write
    self.send_headers()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 346, in send_headers
    self.send_preamble()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 268, in send_preamble
    self._write(
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 467, in _write
    result = self.stdout.write(data)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
OSError: [Errno 41] Protocol wrong type for socket
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54899)
Traceback (most recent call last):
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54890)
Traceback (most recent call last):
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
Traceback (most recent call last):
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 293, in write
    self._write(data)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/wsgiref/handlers.py", line 467, in _write
    result = self.stdout.write(data)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
OSError: [Errno 41] Protocol wrong type for socket
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55297)
Traceback (most recent call last):
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/slyi/opt/miniconda3/envs/higlass-server/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
